# Project
version=1.5.3
group=dev.xylonity.knightlib
java_version=21

# Extra
jei_version=19.21.1.311

# Common
minecraft_version=1.21.1
mod_name=Knight Lib
mod_author=Xylonity
mod_id=knightlib
license=GNU LGPLv3
credits=
description=A Minecraft library mod that serves as a bridge between mods.
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Forge
forge_version=52.0.28
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
